card
Mandhularajitha/E-commerce pull request #3
Opened 2022-02-28 10:58 UTC by Mandhularajitha

2022-02-28 12:16 UTC, samflab requested changes

2022-02-28 12:16 UTC, samflab commented on cards.css
> +    background-color: rgb(117, 249, 253);
use variables for colours

2022-02-28 12:16 UTC, samflab commented on cards.css
> +    height: 550px;
use rem instead of px

2022-02-28 12:16 UTC, samflab commented on cards.css
> +    font-size: 20px;
font size will also be in rem

2022-02-28 12:16 UTC, samflab commented on cards.css
> +    color: white;
use css variables and not colour names

2022-02-28 12:16 UTC, samflab commented on cards.css
> +
put reset.css in another file

2022-02-28 12:16 UTC, samflab commented on cards.html
> +            <p class="product_tittle">Diamond Ring</p>
here title spelling is wrong

2022-02-28 12:19 UTC, samflab commented
Deploy your project on Netlify. It's easier to see the output. 
Please add a description and screenshots to your PR

2022-02-28 12:21 UTC, rutvikpumak commented on cards.html
> +    <title>Document</title>
change title

2022-02-28 12:21 UTC, rutvikpumak commented on cards.css
> +    border: none;
use common reset css for button

2022-02-28 12:21 UTC, rutvikpumak commented on cards.css
> +    background-color: greenyellow;
use css variable for color

2022-02-28 12:25 UTC, rutvikpumak commented
Add all images in a common folder

2022-02-28 12:27 UTC, mohammadkhizerkhan commented on cards.html
> +                <p><i class="fa fa-star" aria-hidden="true"></i></p>
add 5 stars

2022-02-28 17:45 UTC, Sindhu983 approved these changes

2022-03-02 04:36 UTC, NamrataRaikwar2002 approved these changes

2022-03-02 04:45 UTC, merged