shopping-card
Mandhularajitha/E-commerce pull request #5
Opened 2022-02-28 12:36 UTC by Mandhularajitha

2022-02-28 12:38 UTC, mohammadkhizerkhan commented on shoppingcard.css
> +    height: 30px;
image is not responsive

2022-02-28 12:39 UTC, mohammadkhizerkhan commented on shoppingcard.css
> +
image is  not responsive

2022-02-28 12:40 UTC, mohammadkhizerkhan commented on shoppingcard.css
> +    margin-bottom: 30px;
use rem

2022-02-28 16:55 UTC, samflab requested changes

2022-02-28 16:55 UTC, samflab commented on shoppingcard.css
> +}
don't write common css in every file. write it in a separate file then import it here.

2022-02-28 16:55 UTC, samflab commented on shoppingcard.css
> +}
instead of px, use rem. for width use vw.
why do you have to give 1000px? Make it `width: 100%`

2022-02-28 16:55 UTC, samflab commented on shoppingcard.css
> +}
use variables for colour. don't use the RGB value directly.

2022-02-28 17:46 UTC, Sindhu983 approved these changes

2022-03-01 07:32 UTC, simran61 commented on shoppingcard.css
> +    height: 300px;
Try using relative unit instead of px

2022-03-01 07:34 UTC, simran61 commented on shoppingcard.css
> +    height: 300px;
Try using relative units instead of px

2022-03-01 07:35 UTC, simran61 commented on shoppingcard.css
> +    margin-right: 150px;
Try using relative units for all value greater than 10px

2022-03-01 07:36 UTC, simran61 commented on shoppingcard.css
> +    background-color: rgb(108, 226, 108);
instead of RGB values, try using css variables

2022-03-01 07:38 UTC, simran61 commented on shoppingcard.css
> +    border: 1px solid silver;
avoid using color names directly, instead use color variables

2022-03-01 07:39 UTC, simran61 approved these changes

2022-03-02 04:48 UTC, merged